/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "ACK Timeout": {                                 "en": "ACK Timeout",                                     "de": "ACK Timeout",                                     "ru": "ACK Timeout",                                     "pt": "Tempo limite ACK",                                "nl": "ACK Timeout",                                     "fr": "ACK Timeout",                                     "it": "Timeout ACK",                                     "es": "ACK Timeout",                                     "pl": "Limit czasu ACK",                                 "zh-cn": "ACK超时"},
    "AES encrypting": {                              "en": "AES encrypting",                                  "de": "AES-Verschlüsselung",                             "ru": "Шифрование AES",                                  "pt": "Criptografia AES",                                "nl": "AES-codering",                                    "fr": "Cryptage AES",                                    "it": "Crittografia AES",                                "es": "Cifrado AES",                                     "pl": "Szyfrowanie AES",                                 "zh-cn": "AES加密"},
    "AES password": {                                "en": "AES password",                                    "de": "AES Passwort",                                    "ru": "Пароль AES",                                      "pt": "Senha AES",                                       "nl": "AES-wachtwoord",                                  "fr": "Mot de passe AES",                                "it": "Password AES",                                    "es": "Contraseña AES",                                  "pl": "Hasło AES",                                       "zh-cn": "AES密码"},
    "AES password in Hex": {                         "en": "AES password in Hex format",                      "de": "AES Passwort im Hex Format",                      "ru": "Пароль в шестнадцатеричном",                      "pt": "Senha em Hex",                                    "nl": "Wachtwoord in Hex",                               "fr": "Mot de passe en hexadécimal",                     "it": "Password in esadecimale",                         "es": "Contraseña en Hex",                               "pl": "Hasło w Hex",                                     "zh-cn": "十六进制密码"},
    "Accountnumber": {                               "en": "account number",                                  "de": "Accountnummer",                                   "ru": "номер аккаунта",                                  "pt": "número da conta",                                 "nl": "rekeningnummer",                                  "fr": "numéro de compte",                                "it": "numero di conto",                                 "es": "número de cuenta",                                "pl": "numer konta",                                     "zh-cn": "帐号"},
    "IP": {                                          "en": "IP-Address",                                      "de": "IP Adresse",                                      "ru": "Айпи адрес",                                      "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
    "Main settings": {                               "en": "Main settings",                                   "de": "Haupteinstellungen",                              "ru": "Основные настройки",                              "pt": "Configurações principais",                        "nl": "Belangrijkste instellingen",                      "fr": "Réglages principaux",                             "it": "Impostazioni principali",                         "es": "Ajustes principales",                             "pl": "Ustawienia główne",                               "zh-cn": "主要设置"},
    "Port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "Port",                                            "pt": "Port",                                            "nl": "Port",                                            "fr": "Port",                                            "it": "Port",                                            "es": "Port",                                            "pl": "Port",                                            "zh-cn": "港口"},
    "Subscribers": {                                 "en": "Subscribers",                                     "de": "Abonnenten",                                      "ru": "Подписчики",                                      "pt": "Inscritos",                                       "nl": "abonnees",                                        "fr": "Les abonnés",                                     "it": "Iscritti",                                        "es": "Suscriptores",                                    "pl": "Subskrybenci",                                    "zh-cn": "认购"},
    "alarmsystem": {                                 "en": "alarmsystem",                                     "de": "Alarmanlage",                                     "ru": "аварийная система",                               "pt": "sistema de alarme",                               "nl": "alarmsysteem",                                    "fr": "système d'alarme",                                "it": "sistema d'allarme",                               "es": "Sistema de alarmas",                              "pl": "system alarmowy",                                 "zh-cn": "警报系统"},
    "bind": {                                        "en": "Bind IP-Address",                                 "de": "Bind IP-Adresse",                                 "ru": "Связывание IP-адреса",                            "pt": "Vincular endereço IP",                            "nl": "Bind het IP-adres",                               "fr": "Lier l'adresse IP",                               "it": "Bind IP-Address",                                 "es": "Dirección IP de enlace",                          "pl": "Przypisz adres IP",                               "zh-cn": "绑定IP地址"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern wird der Adapter sofort mit der neuen Konfiguration gestartet", "ru": "на перезаписываемом адаптере перезагружается с новой конфигурацией немедленно", "pt": "on save adapter reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur save, l'adaptateur redémarre immédiatement avec la nouvelle configuration", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en guardar adaptador se reinicia con nueva configuración inmediatamente", "pl": "na karcie save natychmiast uruchamia się z nową konfiguracją", "zh-cn": "保存适配器立即重新启动新配置"},
    "subscriber": {                                  "en": "Subscriber",                                      "de": "Abonnement",                                      "ru": "подписчик",                                       "pt": "assinante",                                       "nl": "abonnee",                                         "fr": "abonné",                                          "it": "abbonato",                                        "es": "abonado",                                         "pl": "abonent",                                         "zh-cn": "订户"},
};