// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "on save adapter restarts with new config immediately": {
    "en": "on save adapter restarts with new config immediately",
    "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet."
  },
  "template adapter settings": {
    "en": "template adapter settings",
    "de": "Beispiel"
  },
  "bind": {
    "en": "IP address",
    "de": "IP Adresse"
  },
  "port": {
    "en": "port",
    "de": "Port"
  },
  "subscriber": {
    "en": "subscriber",
    "de": "Subscriber"
  },
  "alarmsystem": {
    "en": "burglar alarm",
    "de": "Alarmanlage"
  }
};
